/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

use std::future::{self, Future};
use std::io::Read;
use std::pin::Pin;

use flate2::read::GzDecoder;
use headers::{ContentType, HeaderMapExt};
use servo::protocol_handler::{
    DoneChannel, FetchContext, NetworkError, ProtocolHandler, Request, ResourceFetchTiming,
    Response, ResponseBody,
};

/// The licenses of the components of the app, generated by `tools/update-licenses.sh`.
static LICENSE_HTML_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/license.html.gz"));

/// Serves the `servo:` URLs: `servo:license` shows the licenses of the components of the app.
pub(crate) struct ServoProtocolHandler;

impl ProtocolHandler for ServoProtocolHandler {
    fn load<'a>(
        &'a self,
        request: &'a mut Request,
        _done_chan: &mut DoneChannel,
        _context: &FetchContext,
    ) -> Pin<Box<dyn Future<Output = Response> + Send + 'a>> {
        let response = match request.current_url().path() {
            "license" => {
                let mut html = Vec::new();
                match GzDecoder::new(LICENSE_HTML_GZ).read_to_end(&mut html) {
                    Ok(_) => html_response(request, html),
                    Err(error) => Response::network_error(NetworkError::ResourceLoadError(
                        format!("Decompressing the licenses failed: {error}"),
                    )),
                }
            },
            _ => Response::network_error(NetworkError::ResourceLoadError(
                "Unknown servo: URL".into(),
            )),
        };
        Box::pin(future::ready(response))
    }
}

fn html_response(request: &Request, html: Vec<u8>) -> Response {
    let mut response = Response::new(
        request.current_url(),
        ResourceFetchTiming::new(request.timing_type()),
    );
    response.headers.typed_insert(ContentType::html());
    *response.body.lock() = ResponseBody::Done(html);
    response
}
